### ISSUE TITLE
关于登陆，搜索以及不可描述内容的消失

### ISSUE THREAD

**Issue by bzxiang** [arakitatsuzou/EhPanda#1]
你好，arakitatsuzouさん！
请问一下最新版本里面，登陆跟搜索的功能为什么被去掉了？
还有不可描述内容无法显示是需要什么特殊的手段吗？
期待您的回复！

**Comment by arakitatsuzou** [comment]
请联系我的Telegram(Tatsuz0u)，我将更新GitHub readme防止出现这种提示不明确的情况，谢谢你的支持。

**Comment by bzxiang** [comment]
Thanks！
