### ISSUE TITLE
[BUG] Filter not working properly

### ISSUE THREAD

**Issue by Yianlaen** [arakitatsuzou/EhPanda#167]
**Describe the bug**

The filter for Doujins, Mangas, etc. , doesn't work when no text is wrote in the search box.

**To Reproduce**
1. Go to the Filters
2. Click to gray out some types like Doujins
3. Refresh the page
4. See that Doujins weren't filtered and still shows up

**Expected behavior**

Filter is still working, even when no text in the search box.

**Screenshots**

Too horny to submit it up. (Just feeling lazy, actually.)

**Please complete the following information:**
 - OS: iOS 15.1
 - App Version: v1.3.7_b118

**Additional context**

If this is designed to be like this, I can accept. Still very thankful for this great app!

~~说起来开发大大是国人我为什么写那么多英文（x~~

**Comment by BurnoutAg7** [comment]
But what should I do if I just want to see categories like Images or Cosplay? There'll always be something excluded if I use a tag or some words in the search box.

**Comment by tatsuz0u** [comment]
Maybe I should make Filters support more list types. 🤔

**Comment by BurnoutAg7** [comment]
I still think filters should be active when search box is empty.

Or enable searching with an empty search box.

**Comment by tatsuz0u** [comment]
As long as you're browsing the Search list, even if the search bar text field is empty, you should still get expected results. 🤔

**Comment by BurnoutAg7** [comment]
You mean using quick search to force an empty search? That's tricky. Anyway thank you. That helps.

**Comment by tatsuz0u** [comment]
I meant if you're browsing the Search list, empty the search bar text field, scroll it to the bottom to trigger load more action, you should get more results already filtered as expected.
