### ISSUE TITLE
Minimum OS version 14.0

### ISSUE THREAD

**Issue by yurimoe** [arakitatsuzou/EhPanda#2]
![C2A239BA-589C-4775-BE7F-96B403E3A72A](https://user-images.githubusercontent.com/24651844/107633537-24ee5400-6ca3-11eb-8404-89f63ef0050b.png)

13.5 :(

**Comment by arakitatsuzou** [comment]
Sorry but it's not an issue but a SwiftUI 2.0 requirement.😢
