### ISSUE TITLE
希望能够从网页跳转或者能直接访问复制的网页连接

### ISSUE THREAD

**Issue by XianYuDaXian** [arakitatsuzou/EhPanda#225]
希望能做到点击网页链接，直接拉起APP，或者可以复制网页链接直接访问。

**Comment by tatsuz0u** [comment]
您好，謝謝您的建議。
您所說的點擊連結跳轉 EhPanda 需要 E-Hentai 的協助，無法獨立完成。
但是 EhPanda 已經支援從剪貼簿偵測畫廊連結和分享表單跳轉，如您無法在分享表單看到 EhPanda，請確保安裝時沒有把 EhPanda 的分享擴充移除。
