### ISSUE TITLE
[BUG]ReducerProtocol 编译无法通过

### ISSUE THREAD

**Issue by HuberyQing** [arakitatsuzou/EhPanda#347]
**Describe the bug**
The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions

**Expected behavior**
build无法通过

**Screenshots**
![image](https://github.com/EhPanda-Team/EhPanda/assets/12196518/fb3b6785-3eab-4076-9b30-1ef1b2a66953)

**Please complete the following information:**
 - Device: [e.g. iPhone 13 Pro]
 - OS: [e.g. iOS 16.6]
 - App Version [e.g. 2.7.2]

**Comment by tatsuz0u** [comment]
您好，感謝您的回報。
短期內我們會嘗試將 Reducer 拆分來改善編譯效能。
但這不是最佳解決方案，我們在計劃一次重構來解決。
