### ISSUE TITLE
[BUG] Error parsing pages on ex source

### ISSUE THREAD

**Issue by M0rtale** [arakitatsuzou/EhPanda#383]
**Describe the bug**
When trying to parse the same repository, on eh source it parses correctly but on ex source it doesn't parse (preview parses correctly and log indicates a correct page of exhentai.org/s/xyz/abc)

**To Reproduce**
Steps to reproduce the behavior on IOS 18.0:
1. Log in to the forum
2. read a repository using ex source
3. read the same repository using eh source
4. See timeout error

**Expected behavior**
page loads and start reading

**Screenshots**
Below is screenshot of the log when fetching from eh source, notice how after parsing the eh URL it begins to parse the images

![image](https://github.com/user-attachments/assets/a4acd68e-31c8-4863-a571-7c87c5b17b24)

Below is screenshot of the log when fetching from ex source, notice how after parsing the ex URL it doesn't parse the image. on an different occasion, I was able to capture the parse failed output

![image](https://github.com/user-attachments/assets/961de677-9d8e-4537-9f86-a9dd937af165)

![image](https://github.com/user-attachments/assets/fb2da30f-6de6-4cfa-a235-99f42b3f7bc5)

**Please complete the following information:**
 - Device: [e.g. iPhone 12]
 - OS: [e.g. iOS 18]
 - App Version [e.g. v2.7.5]

**Additional context**
stopped working after upgrading to IOS 18, DNS set to 8888 8844 (but all URLs can be parsed using my ISP DNS regardless).

**Comment by NyanHeart** [comment]
Same error on iPad with iOS 18.

**Comment by KingOfLife233** [comment]
Same error on iPhone13 with iOS 16.

**Comment by WhiteColloid** [comment]
Same error on iPad pro with iOS 18.0.1 and iPhone13 with iOS 18
![1729918127723](https://github.com/user-attachments/assets/3423a6de-0bbb-4e80-a3af-c39fb4c4ec5e)

**Comment by Haishidalao** [comment]
Same error on iPad air5 with iOS 18.0.1 and iPhone14 with iOS 18

**Comment by OstiumAxioma** [comment]
This error still exist after updating to new version. Only happen on ex sourses.
![image](https://github.com/user-attachments/assets/2f852d68-c579-4186-ad69-342d68ed36be)
